[package]
name = "rgou-ai-core"
version = "0.1.0"
edition = "2021"
authors = ["Robert Gilks"]
description = "Royal Game of Ur AI core logic"
license = "MIT"
repository = "https://github.com/robertgilks/rgou-cloudflare"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
wasm = [
    "wasm-bindgen",
    "console_error_panic_hook",
    "getrandom/js",
    "dep:js-sys",
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
getrandom = { version = "0.2" }
wasm-bindgen = { version = "0.2.100", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = { version = "0.3", optional = true }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
