[package]
name = "rgou-ai-core"
version = "0.1.0"
edition = "2024"
authors = ["Robert Gilks"]
description = "Royal Game of Ur AI core logic"
license = "MIT"
repository = "https://github.com/robertgilks/rgou-cloudflare"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8", features = ["min_const_gen"] }
js-sys = "0.3"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
