name = "rgou-ai-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2023-12-18"
account_id = "571f130502618993d848f58d27ae288d"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.production.vars]
ENVIRONMENT = "production"
