name = "rgou-ai-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-01"
account_id = "571f130502618993d848f58d27ae288d"

[build]
command = "worker-build --release"

[env.production.vars]
ENVIRONMENT = "production"
