name = "rgou-ai-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true
head_sampling_rate = 1

# Uncomment and configure these when ready to deploy
# account_id = "your-account-id"
# workers_dev = true

# Remove routes for now - will be configured during deployment
# [[routes]]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"

[env.development]
name = "rgou-ai-worker-dev"
workers_dev = true

[env.development.vars]
API_SECRET = "dev-secret-key"

[env.staging]
name = "rgou-ai-worker-staging"
workers_dev = true
